1. Random Data File

In [ ]:
import numpy as np

rows, cols = 20000, 10000

with open("ldata.csv", "w") as f:
    for _ in range(rows):
        row = np.random.randint(0, 100, size=cols)
        f.write(",".join(map(str, row)) + "\n")

In [ ]:
with open("ldata.csv", "r") as f:
    count = sum(1 for _ in f)

print("Total rows:", count)

Total rows: 20000


2. Assigning subsequent rows to First Row Elements

In [ ]:
matrix = np.random.randint(1, 10, (5, 5))

print("Original Matrix:\n", matrix)

matrix[0] = np.sum(matrix[1:], axis=0)

print("Updated Matrix:\n", matrix)

Original Matrix:
 [[8 9 7 5 7]
 [8 9 1 3 5]
 [6 6 2 7 2]
 [4 5 8 5 4]
 [1 6 2 7 4]]
Updated Matrix:
 [[19 26 13 22 15]
 [ 8  9  1  3  5]
 [ 6  6  2  7  2]
 [ 4  5  8  5  4]
 [ 1  6  2  7  4]]


3. Grouping Similar Elements into Matrix

In [ ]:
from collections import defaultdict

In [ ]:
matrix = [
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
   ]

groups = defaultdict(list)

for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        groups[matrix[i][j]].append((i, j))

print("Grouped Elements:")
for key, value in groups.items():
    print(key, "->", value)

Grouped Elements:
1 -> [(0, 0), (1, 2), (2, 1)]
2 -> [(0, 1), (1, 0), (2, 2)]
3 -> [(0, 2), (1, 1), (2, 0)]


4. Add and Subtract Matrices

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Sum:\n", A + B)
print("Difference:\n", A - B)

Sum:
 [[ 6  8]
 [10 12]]
Difference:
 [[-4 -4]
 [-4 -4]]


5. n × n Matrix (Opposite Corners Sum = Even)

In [ ]:
n = 4
matrix1 = np.random.randint(0, 10, (n, n))

print("Matrix1:\n", matrix)

valid = True

for i in range(n-1):
    for j in range(n-1):
        if (matrix1[i][j] + matrix1[i+1][j+1]) % 2 != 0:
            valid = False

print("Condition-" , valid)

Matrix1:
 [[1, 2, 3], [2, 3, 1], [3, 1, 2]]
Condition- False


6. Row-wise Element Addition in Tuple Matrix

In [ ]:
matrix = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
row_sums = [sum(row) for row in matrix]
print("Row-wise sums:", row_sums)

Row-wise sums: [6, 15, 24]
